default: &default
  adapter: postgresql
  encoding: unicode
  username: lautaro
  password: 4585
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter-clone_development

test:
  <<: *default
  database: twitter-clone_test

production:
  <<: *default
  database: twitter-clone_production
  username: lautaro
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>